---
- name: Include OS vars
  include_vars: "{{  ansible_os_family  }}.yaml"


- include_tasks: Debian.yaml
- name: Change mysqld.cnf 
  template:
    src: "{{  mysql_cnf }}"
    dest: "{{  mysql_cnf_path  }}"
  notify:
    - Restart mysql
- name: Create user
  mysql_user:
    login_user: root
    login_password: ''
    login_unix_socket: "{{ mysql['socket']  }}"
    check_implicit_admin: yes
    name: "{{  mysql['user']  }}"
    password: "{{  mysql['password'] }}"
    host: "%"
    priv: "{{  mysql['db']  }}.*:ALL,GRANT" 
    state: present

- name: Create Mysql database
  mysql_db:
    login_user: "{{  mysql['user']  }}"
    login_password: "{{  mysql['password']  }}"
    login_unix_socket: "{{  mysql['socket']  }}"
    state: present
    name: "{{  mysql['db']  }}"


